# Generated by Django 5.0 on 2023-12-24 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 8, 10, 15, 748939)),
        ),
    ]
